### ISSUE TITLE
azurecv url

### ISSUE THREAD

**Issue by andriyadi** [vivektiwari1986/azurecv#1]
First of all, thanks for this. Really useful.

I don't is it only me, or there's bug. 
but azurecv URL value should not be using "https://" part, only the domain. Please confirm.

**Comment by vivektiwari1986** [comment]
You are correct. The url should only be the domain without the https:// part.
The url I am using is for example:
tagname.cognitiveservices.azure.com

**Comment by vivektiwari1986** [comment]
Let me know if the above works. I ll update the documentation and close this issue.
