### ISSUE TITLE
Component error: azurecv - Integration 'azurecv' not found

### ISSUE THREAD

**Issue by kaareseras** [vivektiwari1986/azurecv#3]
I have installed the component using HACS, and it worked great for some time, but recently it gives this error

Component error: azurecv - Integration 'azurecv' not found

I have this in config;

azurecv:
  api_key: !secret azurecv_key
  url: !secret azurecv_url

And this is the folder structure

![image](https://user-images.githubusercontent.com/15147387/121484836-e60da800-c9cf-11eb-8e11-d6d44a0f03db.png)

**Comment by henrikbla** [comment]
If you are running the latest version (2021.06) of Home Assistant Core, then it is most likely a consequence of this issue:

https://github.com/vivektiwari1986/azurecv/issues/2

**Comment by kaareseras** [comment]
> If you are running the latest version (2021.06) of Home Assistant Core, then it is most likely a consequence of this issue:
> 
> #2

I'm running core-2021.6.2

I added this to the manifest: "version": "0.0.1"

But no change

**Comment by kaareseras** [comment]
> > If you are running the latest version (2021.06) of Home Assistant Core, then it is most likely a consequence of this issue:
> > #2
> 
> I'm running core-2021.6.2
> 
> I added this to the manifest: "version": "0.0.1"
> 
> But no change

I updated to 221.6.3, and booted, and now it works, with the manual entry in the file

**Comment by vivektiwari1986** [comment]
This should be fixed now.
